
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/sbd-test-project-501910/locations/us-central1/spaces/default-space/applicationTemplates/bb-c7b-tpl

module "cr-1" {
  source                        = "./modules/cr-1"
  project_id                    = var.cr-1_project_id
  location                      = var.cr-1_location
  service_name                  = var.cr-1_service_name
  containers                    = var.cr-1_containers
  gpu_zonal_redundancy_disabled = false
  vpc_access = {
    egress = "PRIVATE_RANGES_ONLY"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
