
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/sbd-test-project-501910/locations/us-central1/spaces/default-space/applicationTemplates/bb-c7b-tpl

provider "google" {
  default_labels = {
    goog-adc-tf-deployment = "export"
  }
}
provider "google-beta" {
  default_labels = {
    goog-adc-tf-deployment = "export"
  }
}
