
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

module "i-row61-comp1" {
  source     = "git::https://staging-us-central1-git.developerconnect.dev/781887672246/conn05/sumanauppala-sketch-repo1//export/app-template-new/modules/service-accounts-1?ref=797f53b647fa71ce20546ba2b1d14cb547a37e1c"
  project_id = var.i-row61-comp1_project_id
  name       = var.i-row61-comp1_name
}
