
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

variable "i-row61-comp1_project_id" {
  description = "Project id where service account will be created"
  type = string
}
variable "i-row61-comp1_name" {
  description = "Name of service account"
  type = string
}
