
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/sbd-test-project-501910/locations/us-central1/spaces/default-space/applicationTemplates/app-template-comp-02-09

provider "google" {
  default_labels = {
    goog-adc-tf-deployment = "export"
  }
  billing_project       = "sbd-test-project-501910"
  user_project_override = true
}
provider "google-beta" {
  default_labels = {
    goog-adc-tf-deployment = "export"
  }
  billing_project       = "sbd-test-project-501910"
  user_project_override = true
}
