
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

module "custom-git-1" {
  source       = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.34.0"
  containers   = var.custom-git-1_containers
  location     = var.custom-git-1_location
  service_name = var.custom-git-1_service_name
  project_id   = var.custom-git-1_project_id
}
