
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/sbd-test-project-501910/locations/us-central1/spaces/default-space/applicationTemplates/local-refernce-variable-test-two

output "cloud-run-1_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.cloud-run-1.service_uri
}
