
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

module "j-row64-custom-comp" {
  source     = "github.com/terraform-google-modules/terraform-google-org-policy?ref=v7.2.0"
  policy_for = var.j-row64-custom-comp_policy_for
  project_id = var.j-row64-custom-comp_project_id
  constraint = var.j-row64-custom-comp_constraint
}
