
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

variable "j-row64-custom-comp_policy_for" {
  description = "Resource hierarchy node to apply the policy to: can be one of `organization`, `folder`, or `project`."
  type = string
}
variable "j-row64-custom-comp_project_id" {
  description = "The project id for putting the policy"
  type = string
}
variable "j-row64-custom-comp_constraint" {
  description = "The constraint to be applied"
  type = string
}
