
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/sbd-test-project-501910/locations/us-central1/spaces/default-space/applicationTemplates/app-template-comp-02-09

module "cloud-storage-1" {
  source             = "github.com/terraform-google-modules/terraform-google-cloud-storage//modules/simple_bucket?ref=v12.3.0"
  project_id         = var.cloud-storage-1_project_id
  location           = var.cloud-storage-1_location
  name               = var.cloud-storage-1_name
  storage_class      = "STANDARD"
  bucket_policy_only = true
  retention_policy = {
    is_locked        = true
    retention_period = 7776000
  }
  lifecycle_rules = [
    {
      action = {
        storage_class = "COLDLINE"
        type          = "SetStorageClass"
      }
      condition = {
        age = 30
      }
    },
  ]
  log_bucket = "jnsnsnjs-logs"
  internal_encryption_config = {
    create_encryption_key = true
    key_rotation_period   = "7776000s"
    prevent_destroy       = false
  }
  depends_on = [
    module.project-services-sbd-test-project-501910,
    module.project-services-billing-project,
  ]
}
module "service-accounts-1" {
  source     = "./modules/service-accounts-1"
  project_id = var.service-accounts-1_project_id
  name       = var.service-accounts-1_name
}
module "apphub" {
  source         = "github.com/GoogleCloudPlatform/terraform-google-apphub?ref=v0.4.0"
  project_id     = var.apphub_project_id
  location       = var.apphub_location
  service_uris   = [module.cloud-storage-1.apphub_service_uri]
  application_id = var.apphub_application_id
}
module "project-services-sbd-test-project-501910" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.2.0"
  project_id                  = "sbd-test-project-501910"
  disable_services_on_destroy = false
  activate_apis = [
    "cloudkms.googleapis.com",
    "iam.googleapis.com",
    "storage.googleapis.com",
  ]
}
module "project-services-billing-project" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.2.0"
  project_id                  = "sbd-test-project-501910"
  disable_services_on_destroy = false
  activate_apis = [
    "apphub.googleapis.com",
    "cloudkms.googleapis.com",
    "cloudresourcemanager.googleapis.com",
    "iam.googleapis.com",
    "serviceusage.googleapis.com",
    "storage.googleapis.com",
  ]
}
