
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/sbd-test-project-501910/locations/us-central1/spaces/default-space/applicationTemplates/app-template-comp-02-09

variable "cloud-storage-1_project_id" {
  description = "The ID of the project to create the bucket in."
  type = string
}
variable "cloud-storage-1_location" {
  description = "The location of the bucket. See https://cloud.google.com/storage/docs/locations."
  type = string
}
variable "cloud-storage-1_name" {
  description = "The name of the bucket."
  type = string
}
variable "service-accounts-1_project_id" {
  description = "Project id where service account will be created"
  type = string
}
variable "service-accounts-1_name" {
  description = "Name of service account"
  type = string
}
variable "apphub_project_id" {
  description = "The project ID of the host project where AppHub application is created."
  type = string
}
variable "apphub_location" {
  description = "The location of AppHub application."
  type = string
}
variable "apphub_application_id" {
  description = "The AppHub application identifier"
  type = string
}
