
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/sbd-test-project-501910/locations/us-central1/spaces/default-space/applicationTemplates/simple-template-two

variable "cloud-storage-1_project_id" {
  description = "The ID of the project to create the bucket in."
  type = string
}
variable "cloud-storage-1_location" {
  description = "The location of the bucket. See https://cloud.google.com/storage/docs/locations."
  type = string
}
variable "cloud-storage-1_name" {
  description = "The name of the bucket."
  type = string
}
