
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

provider "google" {
  default_labels = {
    goog-adc-tf-deployment = "export"
  }
}
provider "google-beta" {
  default_labels = {
    goog-adc-tf-deployment = "export"
  }
}
