
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/sbd-test-project-501910/locations/us-central1/spaces/default-space/applicationTemplates/i-row59-sat

module "i-row59-comp1" {
  source     = "./modules/i-row59-comp1"
  project_id = var.i-row59-comp1_project_id
  name       = var.i-row59-comp1_name
}
