
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/sbd-test-project-501910/locations/us-central1/spaces/default-space/applicationTemplates/i-row59-sat

variable "i-row59-comp1_project_id" {
  description = "Project id where service account will be created"
  type = string
}
variable "i-row59-comp1_name" {
  description = "Name of service account"
  type = string
}
