
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

module "cloud-run-1" {
  source                        = "./modules/cloud-run-1"
  project_id                    = var.cloud-run-1_project_id
  location                      = var.cloud-run-1_location
  service_name                  = var.cloud-run-1_service_name
  containers                    = var.cloud-run-1_containers
  gpu_zonal_redundancy_disabled = false
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "service-accounts-1" {
  source     = "./modules/service-accounts-1"
  project_id = var.service-accounts-1_project_id
  name       = var.service-accounts-1_name
}
module "service-accounts-2" {
  source     = "./modules/service-accounts-2"
  project_id = var.service-accounts-2_project_id
  name       = var.service-accounts-2_name
}
