
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

cloud-run-1_containers = [{
  container_image = "us-docker.pkg.dev/cloudrun/container/hello"
  container_name  = "service-container"
  ports = {
    container_port = 8080
  }
}]
