
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/ai-app-poc-producer/locations/us-central1/spaces/default-space/applicationTemplates/i-row60-sat

module "i-row60-comp1" {
  source     = "./modules/i-row60-comp1"
  project_id = var.i-row60-comp1_project_id
  name       = var.i-row60-comp1_name
}
