
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

module "i-row62-comp1" {
  source     = "github.com/terraform-google-modules/terraform-google-org-policy?ref=v7.2.0"
  policy_for = var.i-row62-comp1_policy_for
  project_id = var.i-row62-comp1_project_id
  constraint = var.i-row62-comp1_constraint
}
