
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/sbd-test-project-501910/locations/us-central1/spaces/default-space/applicationTemplates/app-template-1

module "cloud-run-1" {
  source                        = "./modules/cloud-run-1"
  project_id                    = var.cloud-run-1_project_id
  location                      = var.cloud-run-1_location
  service_name                  = var.cloud-run-1_service_name
  containers                    = var.cloud-run-1_containers
  gpu_zonal_redundancy_disabled = false
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "cloud-storage-1" {
  source        = "./modules/cloud-storage-1"
  project_id    = var.cloud-storage-1_project_id
  location      = var.cloud-storage-1_location
  name          = var.cloud-storage-1_name
  storage_class = "STANDARD"
}
