
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/sbd-test-project-501910/locations/us-central1/spaces/default-space/applicationTemplates/local-refernce-variable-test-two

provider "google" {
  billing_project = "sbd-test-project-501910"
  default_labels = {
    goog-adc-tf-deployment = "export"
  }
  user_project_override = true
}
provider "google-beta" {
  billing_project = "sbd-test-project-501910"
  default_labels = {
    goog-adc-tf-deployment = "export"
  }
  user_project_override = true
}
