
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

module "custom-dc-1" {
  source     = "git::https://staging-us-central1-git.developerconnect.dev/781887672246/conn05/sumanauppala-sketch-repo1//export/app-template-new/modules/service-accounts-1?ref=cad10cd561ba7f7fb386ae57d6be56726b33587f"
  name       = var.custom-dc-1_name
  project_id = var.custom-dc-1_project_id
}
