
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

variable "custom-dc-1_name" {
  description = "Name of service account"
  type = string
}
variable "custom-dc-1_project_id" {
  description = "Project id where service account will be created"
  type = string
}
