
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/ai-app-poc-producer/locations/us-central1/spaces/default-space/applicationTemplates/i-row60-sat

