
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/sbd-test-project-501910/locations/us-central1/spaces/default-space/applicationTemplates/app-template-comp-02-09

module "cloud-storage-1" {
  source             = "./modules/cloud-storage-1"
  project_id         = var.cloud-storage-1_project_id
  location           = var.cloud-storage-1_location
  name               = var.cloud-storage-1_name
  storage_class      = "STANDARD"
  bucket_policy_only = true
  retention_policy = {
    is_locked        = true
    retention_period = 7776000
  }
  lifecycle_rules = [
    {
      action = {
        storage_class = "COLDLINE"
        type          = "SetStorageClass"
      }
      condition = {
        age = 30
      }
    },
  ]
  log_bucket = "jnsnsnjs-logs"
  internal_encryption_config = {
    create_encryption_key = true
    key_rotation_period   = "7776000s"
    prevent_destroy       = false
  }
  depends_on = [
    module.project-services-sbd-test-project-501910,
    module.project-services-billing-project,
  ]
}
module "service-accounts-1" {
  source     = "github.com/terraform-google-modules/terraform-google-service-accounts//modules/simple-sa?ref=v4.7.0"
  project_id = var.service-accounts-1_project_id
  name       = var.service-accounts-1_name
}
module "cloud-run-1" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.33.0"
  project_id                    = var.cloud-run-1_project_id
  location                      = var.cloud-run-1_location
  service_name                  = var.cloud-run-1_service_name
  containers                    = var.cloud-run-1_containers
  gpu_zonal_redundancy_disabled = false
  vpc_access = {
    egress = "PRIVATE_RANGES_ONLY"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "apphub" {
  source         = "github.com/GoogleCloudPlatform/terraform-google-apphub?ref=v0.4.0"
  project_id     = var.apphub_project_id
  location       = var.apphub_location
  service_uris   = concat([module.cloud-storage-1.apphub_service_uri], [module.cloud-run-1.apphub_service_uri])
  application_id = var.apphub_application_id
}
module "project-services-sbd-test-project-501910" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.2.0"
  project_id                  = "sbd-test-project-501910"
  disable_services_on_destroy = false
  activate_apis = [
    "cloudkms.googleapis.com",
    "iam.googleapis.com",
    "storage.googleapis.com",
  ]
}
module "project-services-billing-project" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.2.0"
  project_id                  = "sbd-test-project-501910"
  disable_services_on_destroy = false
  activate_apis = [
    "apphub.googleapis.com",
    "cloudkms.googleapis.com",
    "cloudresourcemanager.googleapis.com",
    "compute.googleapis.com",
    "iam.googleapis.com",
    "iap.googleapis.com",
    "monitoring.googleapis.com",
    "run.googleapis.com",
    "serviceusage.googleapis.com",
    "storage-api.googleapis.com",
    "storage.googleapis.com",
  ]
}
