
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/sbd-test-project-501910/locations/us-central1/spaces/default-space/applicationTemplates/app-template-comp-02-09

cloud-storage-1_project_id = "sbd-test-project-501910"
cloud-storage-1_location   = "us-central1"
cloud-storage-1_name       = "jnsnsnjs"
cloud-run-1_containers = [{
  container_image = "us-docker.pkg.dev/cloudrun/container/hello"
  container_name  = "service-container"
  ports = {
    container_port = 8080
  }
}]
