
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/sbd-test-project-501910/locations/us-central1/spaces/default-space/applicationTemplates/simple-template-two

module "cloud-storage-1" {
  source        = "./modules/cloud-storage-1"
  project_id    = var.cloud-storage-1_project_id
  location      = var.cloud-storage-1_location
  name          = var.cloud-storage-1_name
  storage_class = "STANDARD"
}
